src/keywords/urls.py
from django.urls import path
from .views import DetailProgram, Index
app_name = 'keywords'
urlpatterns = [
    path('', Index.as_view(), name="index"),
    path("detail/<str:slug>", DetailProgram.as_view(), name="program_detail"),
]

src/taitailieu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('keywords.urls')),
    path('summernote/', include('django_summernote.urls')),
]

handler400 = 'keywords.views.bad_request'
handler404 = 'keywords.views.handler404'
handler500 = 'keywords.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/taitl/urls.py
from django.urls import path
from .views import DetailProgram, Index
app_name = 'taitl'
urlpatterns = [
    path('', Index.as_view(), name="index"),
    path("detail/<str:slug>", DetailProgram.as_view(), name="program_detail"),
]

src/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-ND8J2CM');</script>
<!-- End Google Tag Manager -->

    <meta charset="UTF-8">
    {% block title %}
    <title>TảiNhanhPhầnMềm.com - Chia sẻ miễn phí link tải phần mềm</title>
    {% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS-->
    {% load static %}
    <link  rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block cssblock %}
    {% endblock %}

</head>
<body>
    <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-ND8J2CM"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<!--    <header id="header">-->
<!--        <nav class="navbar navbar-dark bg-dark">-->
<!--          <a class="navbar-brand">Kho du lieu</a>-->
<!--          <form class="form-inline">-->
<!--            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--          </form>-->
<!--        </nav>-->
<!--    </header>-->
    <header id="header" class="container-fluid">
        <div class="row container global">
                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div id="logo">
                            <a href="{% url 'keywords:index' %}" title="TảiNhanhPhầnMềm.com - Chia sẻ miễn phí link tải phần mềm">
                                <img width="481" height="68" src="/media/images/logo.png" class="header_logo header-logo" alt="Chia sẻ miễn phí">
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-8 search-form">
                        <div class="flex-col">
                            <input type="search" class="search-field mb-0" name="s" value="" id="s" placeholder="Tìm kiếm" autocomplete="off">
                        </div>
                        <div class="flex-col">
                            <button type="submit" class="ux-search-submit submit-button secondary button icon mb-0" aria-label="Submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
        </div>
    </header>
    {% block main %}
    {% endblock %}

    <footer>
        <div class="container"></div>
    </footer>

</body>
    {% block script %}
    {% endblock %}

</html>

src/templates/core/detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
    <title>Download {{ program.name}}</title>
{% endblock %}
{% block cssblock %}
    <link  rel="stylesheet" href="{% static 'core/css/detail.css' %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="container">
            <div id="content">
               <div class="align-center">
                    <div class="article-inner">
                        <div class="entry-image" style="display: none;">
                            <a href="">
                                <img width="516" height="272" src="{{ program.image.url }}" class="attachment-large size-large wp-post-image" alt="" srcset="" sizes="(max-width: 516px) 100vw, 516px">
                            </a>
                    </div>
                   {% load crispy_forms_tags %}
                    <div class="entry-content">
			{% if user.access == False  %}
			    {{ program.content | safe| linebreaks }}
			{% else %}
                        {% if program.keyword_type == 0 %}
                            <div class="entry-text">
                                <h1 class="entry-title">{{ program.name }}</h1>
                                <p style="color: red; font-weight: bold; margin-bottom: 15px; text-align: center;">***ĐỢT MỘT CHÚT, BẠN CẦN NHẬP PASS***</p>
                            </div>
                            <form action="{% url 'keywords:program_detail' program.slug %}?props={{ data_table.id }}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row justify-content-center">
                                    <div class="col-lg-6 col-md-12">
                                        {{f.code|as_crispy_field}}
                                    </div>
                                </div>
                                <div class="row justify-content-center">
                                    <button type="submit" class="btn btn-primary mb-2">BẤM XEM ĐIỂM </button>
                                </div>
                            </form>

                            <div class="row justify-content-center">
                                {% if check %}
                                    <h4 style="color:green;">Xin lỗi, hệ thống đang bị gián đoạn. Bạn vui lòng thử lại sau.</h4>
                                {% else %}
                                    <h4 style="color:red;">{{ notifi }}</h4>
                                {% endif %}
                            </div>
                		<p>Do tính chất bảo mật, điểm test sẽ được ẩn đi. Để xem điểm, bạn làm theo hướng dẫn bên dưới để lấy Pass nhập vào ô trên. Khi nhập Pass đúng, điểm sẽ hiện.</p>
                        {% else %}
                		<div class="entry-text">
                                	<h1 class="entry-title">***Làm theo hướng dẫn bên dưới để lấy Pass giải nén***</h1>
                            	</div>
                		<div style="border: 1px dashed #007bff; padding: 10px 20px 0 20px; text-align: center; margin-bottom: 20px;">
                    			<p>Bên mình không đặt link rút gọn, hay quảng cáo. Tuy nhiên, Website cũng cần chi phí để duy trì, mong bạn thông cảm giúp về sự bất tiện này.</p>
                		</div>
                        {% endif %}
                	<div style="border: 1px dashed #007bff; padding: 15px 5px 0 5px; text-align: center; margin-bottom: 20px;">  
                        <ul>
                            <li>
                                <div class="row unzip">
                                    <div class="col-sm-6 col-md-12 col-lg-8 text_left">
					<strong>Bước 1:</strong> Vào trang tìm kiếm
					<a href="https://google.com.vn" target="_blank" style="color: #007bff; font-weight: bold; text-decoration: none">Google.com.vn</a>
					gõ từ khóa (Bạn bấm sao chép cho nhanh)
				    </div>
                                    <div class="col-sm-6 col-md-12 col-lg-4 button_right">
					<input type="text" value="{{ data_table.keyword }}" id="ikey" readonly="readonly">
					<button onclick="copyToClipboard()" id="buco" style="font-size: 13px;">Sao chép
					</button>
				    </div>
                                </div>
                            </li>
                            <li>
                                <strong>Bước 2:</strong> <span style="color: red; font-weight: bold;">Sử dụng điện thoại di động</span>, Tìm ở <span style="color: red; font-weight: bold;">trang 1</span> hoặc <span style="color: red; font-weight: bold;">trang 2</span> của kết quả tìm kiếm và click vào bài viết như hình dưới đây: <span style="font-style: italic;">(bạn xem đúng tiêu đề, tránh click nhầm trang sẽ không có Pass)</span>
                            </li>
                        </ul>
                        <p>
                            <img class="alignnone size-full wp-image-1864" src="{{ data_table.image.url }}" width="100%" height="auto">
                        </p>
                        <ul>
                            <li><strong>Bước 3:</strong> Vào web, kéo xuống dưới, phần <span style="color: red; font-weight: bold;">TÔ ĐỎ</span> <strong>là pass</strong>:</li>
                        </ul>
                        <p>
                            <img class="alignnone size-full wp-image-1864" src="{{ data_table.image2.url }}" width="100%" height="auto">
                        </p>
                    	</div>
		    {% endif %}
                    </div>
               </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script>
    function copyToClipboard() {
    var textBox = document.getElementById("ikey");
    var nameButton = document.getElementById("buco");
    textBox.select();
    document.execCommand("copy");
    nameButton.innerHTML = "Đã copy";
}
</script>

{% endblock %}

src/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chia sẽ miễn phí</title>
    <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!--Bootstrap CSS-->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>

</body>
</html>

src/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
    <title>TảiNhanhPhầnMềm.com - Chia sẻ miễn phí link tải phần mềm</title>
{% endblock %}

{% block cssblock %}
    <link rel="stylesheet" href="{% static 'core/css/index.css' %}">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/dist/css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/less/mixins/grid-framework.less">
{% endblock %}
{% block main %}
    <div class="container" id="wrapper">
        <div id="content">
            <section class="section">
                <div class="section-content">
                    <div id="gap-708874946"></div>
                    <div class="section-title-container">
                        <h2 class="section-title section-title-center"><b></b><span class="section-title-main" style="color:rgb(255, 177, 17);">Phần Mềm</span><b></b></h2>
                    </div>
                    <div class="row">
                        {% for p in program %}
                        <div class="col-sm-6 col-md-4 col-lg-3 post-item">
                            <div class="col-inner">
                                <a href="{% url 'keywords:program_detail' p.slug %}">
                                    <div class="box">
                                        <div class="box-image">
                                            <div class="image-cover">
                                                <img width="1020" class="full zoom" height="574" src="{{ p.image.url }}" class="attachment-large size-large wp-post-image" alt="" srcset="" sizes="(max-width: 1020px) 100vw, 1020px">
                                            </div>
                                        </div>
                                        <div class="box-text">
                                            <div class="box-text-inner">
                                                <h3 class="post-title">{{ p.name }}</h3>
                               
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
            
        </div>
    </div>
{% endblock %}

src/templates/core/program.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
    <title>Tai</title>
{% endblock %}

{% block main %}
    <div id="main">
        <div class="row justify-content-center">
            <img src="/media/images/logo.png" sizes="(max-width: 516px) 100vw, 516px">
        </div>

        <div class="row justify-content-center">
            <h1 class="entry-title">Tải abc full</h1>
        </div>
        {% load crispy_forms_tags %}
        <div class="row justify-content-center">
            <form class="form-inline" action="{% url 'core:program_detail' program.slug %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="form-group mb-2">
                {{f.code}}
              </div>
              <button type="submit" class="btn btn-primary mb-2">Enter</button>
            </form>
        </div>
        <div class="row justify-content-center">
            {% if check %}
                <span>{{ program.link }}</span>
            {% else %}
                <span> {{ notifi }} </span>
            {% endif %}
        </div>

    </div>
{% endblock %}